{% set version = "1.2" %}

package:
  name: polycap
  version: {{ version }}

source:
  url: https://github.com/PieterTack/polycap/releases/download/v{{ version }}/polycap-{{ version }}.tar.xz
  sha256: 6e08a8f5ae29f7948a10aa75806bbf11a401ac735de903d4c574b22c25b18dce

build:
  number: 5

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - meson
    - ninja
    - cython
    - pkg-config  # [unix]
    # using the mingw build of pkg-config seems to be essential,
    # as it seems to handle the broken hdf5.pc gracefully.
    - m2w64-pkg-config  # [win]
  host:
    - python
    - hdf5
    - gsl
    - numpy
    - xraylib
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - zlib
    - setuptools
  run:
    - python
    - hdf5
    - gsl
    - libopenblas
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ pin_compatible('xraylib') }}

test:
  imports:
    - polycap
  commands:
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libpolycap.pc exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\polycap.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\polycap\\polycap.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\polycap-2.dll exit 1  # [win]

about:
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  home: https://github.com/PieterTack/polycap
  summary: Polycapillary X-ray raytracing

extra:
  recipe-maintainers:
    - tschoonj
    - PieterTack
