{% set version = "1.0" %}

package:
  name: polycap
  version: {{ version }}

source:
  url: https://github.com/PieterTack/polycap/releases/download/v{{ version }}/polycap-{{ version }}.tar.gz
  sha256: e181378eb3eb3479e87cdedc8bfb326e524999abf06b99e3a1a9528ba4f0608b

build:
  number: 1

requirements:
  build:
    - m2-bash  # [win]
    - m2-coreutils  # [win]
    - m2-diffutils  # [win]
    - m2-gawk  # [win]
    - m2-grep  # [win]
    - m2-make  # [win]
    - m2-sed  # [win]
    - m2-which  # [win]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]  
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - pkg-config  # [unix]
    - m2w64-pkg-config  # [win]
    - m2w64-binutils  # [win]
    - m2w64-gcc  # [win]
    - m2w64-tools-git  # [win]
  host:
    - python
    - cython
    - hdf5
    - gsl
    - numpy >=1.14
    - xraylib >=4.0.0
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - m2w64-binutils  # [win]
    - m2w64-gcc  # [win]
    - m2w64-tools-git  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5
    - gsl
    - libopenblas
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - xraylib >=4.0.0
    - zlib

test:
  imports:
    - polycap

about:
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  home: https://github.com/PieterTack/polycap
  summary: Polycapillary X-ray raytracing

extra:
  recipe-maintainers:
    - tschoonj
    - PieterTack
